package response

var ParameterMissing string = "One of the required parameter is missing"
var ProductidInvalid string = "Product id is invalid"
var ProductsAddedToCart string = "Respective products have been successfully added to the cart"
var ProductDetailAdded string = "Product detail has been inserted"
var ProductDetailDeleted string = "Product detail has been deleted sucessfully"
var ProductDetailUpdated string = "Product detail has been updated "
var ProductNotFound string = "Product does not exist"
var ReferenceIdNotExist string = "Reference_id doesn't exists"
var DataNotFound string = "NO DATA FOUND"
var ReferenceOrProductidMissing string = "ref / product_id missing in the url"
var CartItemDeleted string = "Cart item deleted successfully"
var InvalidCartRef string = "Invalid cart_reference"
var ProductNotInCart string = "Product is not found in your cart"
var CategoryDetailAdded string = "Category detail has been added successfully"
var CategoryIdDoesNotExist string = "The value category_id does not exist,enter a Valid ID"
var CategoryDetailDeleted string = "The category detail has been deleted successfully"
var CategoryidNotPresent string = "Category id not present"
var CategoryDetailUpdated string = "Category details have been updated"
var InventoryDetailAdded string = "Inventory detail has been added successfully"
var ProductidDoesNotExist string = "The value product_id does not exist, please enter a Valid ID"
var InventoryDetailDeleted string = "The inventory detail has been deleted successfully"
var InventoryDetailUpdate string = "Inventory detail has been  has been updated successfully!"
var InventoryidDoesExist string = "Inventory id doesn't exist"
